# Generated by Django 4.0.3 on 2022-03-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permissions',
            field=models.CharField(choices=[('AUT', 'auteur'), ('COL', 'collaborateur')], max_length=15),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('BE', 'back-end'), ('FE', 'front-end'), ('IOS', 'ios'), ('AND', 'android')], max_length=128),
        ),
    ]
